<a href="https://colab.research.google.com/github/SurekhaBerlin/NPower-Python-Practices/blob/main/nlp_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a = np.array([[1,2,3,4,3,2],[5,6,7,8,12,21],[6,4,32,7,8,10],[5,22,7,8,15,21],[15,12,26,17,8,12]])

In [ ]:
a

array([[ 1,  2,  3,  4,  3,  2],
       [ 5,  6,  7,  8, 12, 21],
       [ 6,  4, 32,  7,  8, 10],
       [ 5, 22,  7,  8, 15, 21],
       [15, 12, 26, 17,  8, 12]])

Extract all 3 rows of teh last 4 columns in a given numpy 2D array a ?

In [ ]:
a[:3,-5:]

array([[ 2,  3,  4,  3,  2],
       [ 6,  7,  8, 12, 21],
       [ 4, 32,  7,  8, 10]])

In [ ]:
a[:4,2:]

array([[ 3,  4,  3,  2],
       [ 7,  8, 12, 21],
       [32,  7,  8, 10],
       [ 7,  8, 15, 21]])

Give apositive number greater than 2,create a numpy array of size (n*n) with all zeros and ones such that the ones makes the shape of " + "

In [ ]:
n = 5

In [ ]:
z = np.zeros((n,n),dtype = 'int')
print (z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
# Make the middle row and column all 1s

In [ ]:
z[n//2,:]=1
z[:,n//2]=1

print(z)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [1]:
txt = "Hello, And Welcome to My World"